name: Build Windows x64 with MinGW

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-windows-mingw64.yml"
      - "CMakeLists.txt"
      - "RedPandaIDE/**"
      - "libs/**"
      - "packages/**"
      - "platform/windows/**"
      - "tools/**"
      - "version.json"
  pull_request:
    paths:
      - ".github/workflows/build-windows-mingw64.yml"
      - "CMakeLists.txt"
      - "RedPandaIDE/**"
      - "libs/**"
      - "packages/**"
      - "platform/windows/**"
      - "tools/**"
      - "version.json"

permissions:
  contents: read

jobs:
  windows_mingw64:
    name: Windows x64 MinGW
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true

      - name: Build
        run: |
          ./packages/mingw/build-xp.sh -p 64-ucrt --mingw

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64 MinGW
          path: dist/*
